/*
Name:  ApplicationException.cls
Copyright © 2016  Sylvain Picory
======================================================
======================================================
Purpose:
-------

This class will be used to handle custom exception in the application

======================================================
======================================================
History
------- 
Ver. Author        	   Date        Detail
1.0  Sylvain Picory    2016-10-25  Initial draft of code.
*/
public class ApplicationException extends Exception {

}